### ISSUE TITLE
Hunk #1 FAILED at 9: UploadCustomImageHint.tsx

### ISSUE THREAD

**Issue by Akram-MA** [KosmX/incus-ui-canonical-arch#1]
Failed at makepkg:

==> Making package: incus-ui-canonical 0.5-1 (Sun 18 Feb 2024 12:40:46 PM +03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating incus git repo...
  -> Found 0.5.tar.gz
  -> Found incus.service
==> Validating source files with sha256sums...
    incus ... Skipped
    0.5.tar.gz ... Passed
    incus.service ... Passed
==> Extracting sources...
  -> Creating working copy of incus git repo...
Reset branch 'makepkg'
  -> Extracting 0.5.tar.gz with bsdtar
==> Starting prepare()...
patching file src/components/Navigation.tsx
Hunk #1 succeeded at 287 (offset 1 line).
Hunk #2 succeeded at 302 (offset 1 line).
patching file src/components/NoMatch.tsx
patching file src/context/useDocs.tsx
patching file src/pages/login/BrowserImport.tsx
patching file src/pages/login/CertificateAdd.tsx
patching file src/pages/login/CertificateGenerate.tsx
patching file src/util/certificate.tsx
patching file src/pages/storage/UploadCustomImageHint.tsx
Hunk #1 FAILED at 9.
1 out of 1 hunk FAILED -- saving rejects to file src/pages/storage/UploadCustomImageHint.tsx.rej
==> ERROR: A failure occurred in prepare().
    Aborting...

**Comment by KosmX** [comment]
Can you please try it again?  
> package has been updated to lxd-ui 0.6, this should be fixed.
