### ISSUE TITLE
Branding patch not applied (missing Logo..)

### ISSUE THREAD

**Issue by jkerdreux-imt** [KosmX/incus-ui-canonical-arch#3]
The Branding patch (logo, icons ..) is skipped (/patches/ui-canonical-0001-Branding.patch) 
When I turn on --verbose on the git apply in the PKGBUILD file I get this : 

```
Skipped patch 'index.html'.
Skipped patch 'public/assets/img/favicon-32x32.png'.
Skipped patch 'public/assets/img/incus-logo.svg'.
Skipped patch 'public/assets/img/lxd-logo.svg'.
Skipped patch 'src/components/Logo.tsx'.
Skipped patch 'src/pages/login/Login.tsx'.
Skipped patch 'src/sass/_pattern_icon.scss'.
Skipped patch 'src/sass/_pattern_navigation.scss'.
Skipped patch 'src/sass/styles.scss'.
Skipped patch 'src/util/title.tsx'.
```
The main issue is: git apply doesn't work here because your code is in a git repo. A rapid test (deleting your .git folder) and then building works fine. No more skipped patch, and nice a Incus Logo.

Tested w/ version 0.8 but exists in previous versions. In 0.6 and 0.7 it displays the canonical title and logo. In 0.8 wrong title and missing logo.

**Comment by KosmX** [comment]
Apparently building in chroot is a bad idea if I want to catch git issues.  

The patch for the favicon is a git binary change, `diff` can't apply that, only `git`. However I have no idea, how to tell git to ignore all git repos and use the actual folder as the working repository. 



If I don't find any other solution, doing a `git init` can help.

**Comment by jkerdreux-imt** [comment]
I tested with --directory without any success.
```
 git apply --verbose --directory=$(pwd) -p1 < ...
```
But git init just before the git apply do the trick.
